server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            #- After=2023-03-28T23:43:40.310+08:00[Asia/Shanghai]  #指定时间之后的请求才会进行转发
            #- Cookie=username,hsy  #携带Cookie 且username=hsy
          #filters:
            #- PrefixPath=/payment  #在请求路径上增加一个前缀 /payment
            # AddRequestHeader=my-request-header,1024  #拦截传入的请求，并在请求上添加一个指定的请求头参数。

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka